import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import StickyMobileCTA from "@/components/StickyMobileCTA";
import Breadcrumbs from "@/components/Breadcrumbs";
import JsonLd from "@/components/JsonLd";
import StickyNav from "@/components/StickyNav";

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
});

const outfit = Outfit({
    subsets: ['latin'],
    variable: '--font-outfit',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "JPD Complete Electrical | Professional Electrician Adelaide",
    // 155 chars, so Google shows the whole thing rather than cutting mid-sentence.
    description: "Licensed Adelaide electrician for switchboard upgrades, EV chargers, downlights, safety switches and emergency callouts. Owner-operated. Free quotes.",
    // The `keywords` meta tag is deliberately absent. Google has ignored it since
    // 2009, and it published our entire target list to any competitor viewing source.
    icons: {
        icon: [
            {
                url: '/favicon-theme-light.png', // Default for search engines/crawlers (Navy)
            },
            {
                url: '/favicon-theme-light.png',
                media: '(prefers-color-scheme: light)',
            },
            {
                url: '/favicon-theme-dark.png',
                media: '(prefers-color-scheme: dark)',
            },
        ],
    },
    metadataBase: new URL('https://jpdcompleteelectrical.com.au'),
    alternates: {
        canonical: '/',
    },
    openGraph: {
        title: 'JPD Complete Electrical | Electrician Adelaide',
        description: 'Reliable. Honest. Professional. Licensed Adelaide electrician for switchboards, EV chargers, lighting and emergency callouts.',
        url: 'https://jpdcompleteelectrical.com.au',
        siteName: 'JPD Complete Electrical',
        images: [
            {
                // Generated by scripts/optimise-images.mjs. This previously pointed at
                // google-logo.png, a 96x96 favicon declared as 1200x630, so every
                // Facebook, LinkedIn, WhatsApp and Slack share rendered a tiny icon
                // or nothing at all.
                url: '/og-card.png',
                width: 1200,
                height: 630,
                alt: 'JPD Complete Electrical - Licensed Adelaide Electrician',
            },
        ],
        locale: 'en_AU',
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: 'JPD Complete Electrical | Electrician Adelaide',
        description: 'Reliable. Honest. Professional. Licensed Adelaide electrician for switchboards, EV chargers, lighting and emergency callouts.',
        images: ['/og-card.png'],
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${inter.variable} ${outfit.variable} scroll-smooth`}>
            <head>
                <JsonLd />
            </head>
            <body className="antialiased text-navy bg-white flex flex-col min-h-screen">
                <Header />
                <StickyNav />
                <Breadcrumbs />
                <main className="flex-grow">
                    {children}
                </main>
                <Footer />
                <ScrollToTop />
                <StickyMobileCTA />
            </body>
        </html>
    );
}
